[package]
name = "morset"
version = "0.1.0"
edition = "2021"
description = "MORSE code Translator / cheat sheet"
license = "MIT"
keywords = ["morse_code", "morse", "translator"]
categories = ["encoding", "text-processing"]

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
